
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analyze;

/** CUP generated class containing symbol constants. */
public class Terminal {
  /* terminals */
  public static final int TK_Equal = 7;
  public static final int TK_KW_InitialState = 13;
  public static final int TK_Slash = 23;
  public static final int TK_LessT = 5;
  public static final int TK_Point = 4;
  public static final int TK_Colon = 22;
  public static final int TK_Plus = 2;
  public static final int TK_KW_AP = 25;
  public static final int TK_Left_Brace = 16;
  public static final int TK_KW_NumberStates = 11;
  public static final int TK_KW_Nombre = 9;
  public static final int TK_Hash = 26;
  public static final int EOF = 0;
  public static final int TK_Arrow = 24;
  public static final int TK_Left_Parenthesis = 29;
  public static final int TK_Coma = 18;
  public static final int TK_String = 10;
  public static final int TK_Right_Parenthesis = 30;
  public static final int TK_OR = 20;
  public static final int error = 1;
  public static final int TK_Number = 3;
  public static final int TK_KW_Desc = 31;
  public static final int TK_Right_Brace = 17;
  public static final int TK_Dollar = 27;
  public static final int TK_KW_AcceptStates = 14;
  public static final int TK_KW_Simbols = 28;
  public static final int TK_SemiColon = 19;
  public static final int TK_KW_Alphabet = 12;
  public static final int TK_KW_VerAutomatas = 32;
  public static final int TK_KW_Transiciones = 21;
  public static final int TK_KW_AFD = 8;
  public static final int TK_GreatherT = 6;
  public static final int TK_ID = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TK_Plus",
  "TK_Number",
  "TK_Point",
  "TK_LessT",
  "TK_GreatherT",
  "TK_Equal",
  "TK_KW_AFD",
  "TK_KW_Nombre",
  "TK_String",
  "TK_KW_NumberStates",
  "TK_KW_Alphabet",
  "TK_KW_InitialState",
  "TK_KW_AcceptStates",
  "TK_ID",
  "TK_Left_Brace",
  "TK_Right_Brace",
  "TK_Coma",
  "TK_SemiColon",
  "TK_OR",
  "TK_KW_Transiciones",
  "TK_Colon",
  "TK_Slash",
  "TK_Arrow",
  "TK_KW_AP",
  "TK_Hash",
  "TK_Dollar",
  "TK_KW_Simbols",
  "TK_Left_Parenthesis",
  "TK_Right_Parenthesis",
  "TK_KW_Desc",
  "TK_KW_VerAutomatas"
  };
}

